export const variables = {
    HrdbDepartmentData: {
        _id: "wm-HrdbDepartmentData-wm.LiveVariable-1564572740121",
        name: "HrdbDepartmentData",
        owner: "Page",
        category: "wm.LiveVariable",
        dataBinding: [],
        operation: "read",
        dataSet: [],
        type: "Department",
        isList: true,
        saveInPhonegap: false,
        maxResults: 20,
        designMaxResults: 10,
        inFlightBehavior: "executeLast",
        startUpdate: true,
        autoUpdate: true,
        transformationRequired: false,
        liveSource: "hrdb",
        ignoreCase: true,
        matchMode: "startignorecase",
        orderBy: "deptId asc",
        propertiesMap: {
            columns: [
                {
                    fieldName: "deptId",
                    type: "integer",
                    fullyQualifiedType: "integer",
                    columnName: "DEPT_ID",
                    isPrimaryKey: true,
                    notNull: true,
                    length: 255,
                    precision: 10,
                    generator: "identity",
                    isRelated: false,
                    scale: 0
                },
                {
                    fieldName: "name",
                    type: "string",
                    fullyQualifiedType: "string",
                    columnName: "NAME",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                },
                {
                    fieldName: "budget",
                    type: "integer",
                    fullyQualifiedType: "integer",
                    columnName: "BUDGET",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 10,
                    generator: "assigned",
                    isRelated: false,
                    scale: 0
                },
                {
                    fieldName: "q1",
                    type: "integer",
                    fullyQualifiedType: "integer",
                    columnName: "Q1",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 10,
                    generator: "assigned",
                    isRelated: false,
                    scale: 0
                },
                {
                    fieldName: "q2",
                    type: "integer",
                    fullyQualifiedType: "integer",
                    columnName: "Q2",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 10,
                    generator: "assigned",
                    isRelated: false,
                    scale: 0
                },
                {
                    fieldName: "q3",
                    type: "integer",
                    fullyQualifiedType: "integer",
                    columnName: "Q3",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 10,
                    generator: "assigned",
                    isRelated: false,
                    scale: 0
                },
                {
                    fieldName: "q4",
                    type: "integer",
                    fullyQualifiedType: "integer",
                    columnName: "Q4",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 10,
                    generator: "assigned",
                    isRelated: false,
                    scale: 0
                },
                {
                    fieldName: "deptCode",
                    type: "string",
                    fullyQualifiedType: "string",
                    columnName: "DEPT_CODE",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 20,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                },
                {
                    fieldName: "location",
                    type: "string",
                    fullyQualifiedType: "string",
                    columnName: "LOCATION",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 19,
                    generator: "assigned",
                    isRelated: false,
                    scale: 2
                },
                {
                    fieldName: "tenantId",
                    type: "integer",
                    fullyQualifiedType: "integer",
                    columnName: "TENANT_ID",
                    isPrimaryKey: false,
                    notNull: false,
                    length: 255,
                    precision: 10,
                    generator: "assigned",
                    isRelated: false,
                    scale: 0
                }
            ],
            entityName: "Department",
            fullyQualifiedName: "com.wmperflistproj.hrdb.Department",
            tableType: "TABLE",
            primaryFields: ["deptId"]
        },
        isDefault: true,
        bindCount: 1,
        tableName: "DEPARTMENT",
        tableType: "TABLE",
        properties: [],
        relatedTables: [],
        filterExpressions: {},
        package: "com.wmperflistproj.hrdb.Department"
    }
}

export const getVariables = () => JSON.parse(JSON.stringify(variables))
